global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "windows_exporter"
    static_configs:
      - targets: ["localhost:9182"] 

  - job_name: "linux_exporter"
    static_configs:
      - targets: ["localhost:9100"]  

  - job_name: "mac_exporter"
    static_configs:
      - targets: ["localhost:9100"]
